# Site settings
title: Gian Guitar
email: gtrsage@gmail.com
description: Handcrafted guitar development through lessons, instructions, sessions & consultations.
baseurl: "/giansolo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title/

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/gianaudio
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/gian_solo/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/gian_solo

# Build settings
markdown: kramdown
